# Generated by Django 4.1.7 on 2023-03-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honour',
            name='person',
            field=models.CharField(help_text='Bitte gib den Namen der Person an.', max_length=800),
        ),
        migrations.AlterField(
            model_name='position',
            name='person',
            field=models.CharField(help_text='Bitte gib den Namen der Person an.', max_length=800),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='slogan',
            field=models.TextField(blank=True, help_text='Du kannst ein Motto oder ein Thema für das Jahr angeben. Ist dieses Feld leer, wird nichts angezeigt.'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='title',
            field=models.CharField(blank=True, help_text='Du kannst einen abweichenden Titel für die Slide angeben. Ist dieses Feld leer, wird das Jahr angezeigt.', max_length=800),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
