# Generated by Django 4.1.7 on 2023-03-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_honour_person_alter_position_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='chairmen',
            field=models.BooleanField(default=False, help_text='Bitte gib an, ob die Person Vorsitzender war.'),
        ),
    ]
