# Generated by Django 4.1.7 on 2023-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0006_remove_yearslide_pdf_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearslide',
            name='document',
            field=models.FileField(blank=True, help_text='Du kannst eine PDF-Datei hochladen, die zu diesem Jahr gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to='media/pdfs/'),
        ),
        migrations.AddField(
            model_name='yearslide',
            name='document_image',
            field=models.ImageField(blank=True, help_text='Du kannst ein Vorschaubild hochladen, das zu diesem Dokument gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to='media/images/'),
        ),
    ]
