# Generated by Django 4.1.7 on 2023-04-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0008_highlight_remove_image_year_delete_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(help_text='Bitte lade ein Bild hoch.', upload_to=''),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='document',
            field=models.FileField(blank=True, help_text='Du kannst eine PDF-Datei hochladen, die zu diesem Jahr gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='document_image',
            field=models.ImageField(blank=True, help_text='Du kannst ein Vorschaubild hochladen, das zu diesem Dokument gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to=''),
        ),
    ]
