# Generated by Django 4.1.7 on 2023-04-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0009_alter_highlight_image_alter_yearslide_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Bitte lade ein Bild hoch.', upload_to='')),
                ('description', models.TextField(help_text='Bitte gib eine Beschreibung für das Event an.')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.yearslide')),
            ],
        ),
    ]
