# Generated by Django 4.1.7 on 2023-05-04 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0010_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'verbose_name': 'Highlight'},
        ),
        migrations.AlterModelOptions(
            name='honour',
            options={'verbose_name': 'Ehrung', 'verbose_name_plural': 'Ehrungen'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Einzelbild', 'verbose_name_plural': 'Einzelbilder'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Person / Rolle', 'verbose_name_plural': 'Personen / Rollen'},
        ),
        migrations.AlterModelOptions(
            name='yearslide',
            options={'verbose_name': 'Jahresrückblick (Jahr)', 'verbose_name_plural': 'Jahresrückblicke (Jahre)'},
        ),
        migrations.AlterField(
            model_name='highlight',
            name='date',
            field=models.DateField(help_text='Bitte gib das Datum für das Event an.', verbose_name='Veranstaltungsdatum'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(help_text='Bitte gib eine Beschreibung für das Event an.', verbose_name='Beschreibung / Text'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(help_text='Bitte lade ein Bild hoch. Bevorzugt einzelen Bilder mit einem Motiv im Mittelpunkt.', upload_to='', verbose_name='Foto / Bild'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='location',
            field=models.CharField(help_text='Bitte gib den Ort für das Event an.', max_length=800, verbose_name='Veranstaltungsort'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(help_text='Bitte gib einen Titel für das Bild an.', max_length=800, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.yearslide', verbose_name='Jahresrückblick / Jahr'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='honour',
            field=models.CharField(help_text='Bitte gib die Auszeichnung an, die die Person im Jahr erhalten hat.', max_length=800, verbose_name='Name der Ehrung'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='person',
            field=models.CharField(help_text='Bitte gib den Namen der Person an.', max_length=800, verbose_name='Name der Person'),
        ),
        migrations.AlterField(
            model_name='honour',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.yearslide', verbose_name='Jahresrückblick / Jahr'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(help_text='Bitte gib eine Beschreibung an - zum Beispiel Anlass, Datum, Ort,...', verbose_name='Beschreibung / Titel'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Bitte lade ein Bild hoch.', upload_to='', verbose_name='Foto / Bild'),
        ),
        migrations.AlterField(
            model_name='image',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.yearslide', verbose_name='Jahresrückblick / Jahr'),
        ),
        migrations.AlterField(
            model_name='position',
            name='chairman',
            field=models.BooleanField(default=False, help_text='Bitte gib an, ob die Person Vorsitzender war.', verbose_name='Ist Vorsitzender?'),
        ),
        migrations.AlterField(
            model_name='position',
            name='person',
            field=models.CharField(help_text='Bitte gib den Namen der Person an.', max_length=800, verbose_name='Name der Person'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(help_text='Bitte gib die Position an, die die Person im Jahr innehatte.', max_length=800, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.yearslide', verbose_name='Jahresrückblick / Jahr'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='document',
            field=models.FileField(blank=True, help_text='Du kannst eine PDF-Datei hochladen, die zu diesem Jahr gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to='', verbose_name='Jahresrückblick (PDF)'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='document_image',
            field=models.ImageField(blank=True, help_text='Du kannst ein Vorschaubild hochladen, das zu diesem Dokument gehört. Ist dieses Feld leer, wird nichts angezeigt.', null=True, upload_to='', verbose_name='Jahresrückblick (Titelbild)'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='slogan',
            field=models.TextField(blank=True, help_text='Du kannst ein Motto oder ein Thema für das Jahr angeben. Ist dieses Feld leer, wird nichts angezeigt.', verbose_name='Motto'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='title',
            field=models.CharField(blank=True, help_text='Du kannst einen abweichenden Titel für die Slide angeben. Ist dieses Feld leer, wird das Jahr angezeigt.', max_length=800, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='yearslide',
            name='year',
            field=models.IntegerField(help_text='Bitte gib das Jahr an, für das du diesen Slide erstellen möchtest. Nach diesem Wert wird sortiert.', verbose_name='Jahreszahl'),
        ),
    ]
